/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/ui/button/Button.vue')['default']
    FormControl: typeof import('./components/ui/form/FormControl.vue')['default']
    FormDescription: typeof import('./components/ui/form/FormDescription.vue')['default']
    FormItem: typeof import('./components/ui/form/FormItem.vue')['default']
    FormLabel: typeof import('./components/ui/form/FormLabel.vue')['default']
    FormMessage: typeof import('./components/ui/form/FormMessage.vue')['default']
    Icon: typeof import('./components/ui/icon/Icon.vue')['default']
    Input: typeof import('./components/ui/input/Input.vue')['default']
    Label: typeof import('./components/ui/label/Label.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spinner: typeof import('./components/ui/Spinner.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    WeatherCard: typeof import('./components/WeatherCard.vue')['default']
  }
}
